spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: account
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
  timelimiter:
    instances:
      default:
        timeout-duration: 2s
       
web:
  baseurl:
    creditservice: http://localhost:8083
    customerservice: http://localhost:8080/customers
    transactionservice: http://localhost:8082/transactions
