spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: account

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        record-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout
        ignore-exceptions:
          - org.springframework.web.server.ResponseStatusException
          - org.springframework.web.reactive.function.client.WebClientResponseException$NotFound
          - org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
  timelimiter:
    instances:
      default:
        timeout-duration: 2s