spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: account
      
eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
  timelimiter:
    instances:
      default:
        timeout-duration: 2s