spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: customer

eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
  timelimiter:
    instances:
      default:
        timeout-duration: 2s
 
application:
  jwt:
    key: brXzPetE8ivZhetRar0MW47UcUJg8GL5hdmnSvFk2nYQdxSWkLZHLWUftkzKaPyA
    expiration: 900000 # 15 minutes

web:
  baseurl:
    accountservice: http://localhost:8081
    creditservice: http://localhost:8083